name: Update SVG List
on:
  push:
    branches: 
      - main 

jobs:
  updatesvgList: # you can put any name here
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout repo
      - shell: bash
        run: find . -name "*.svg" -print > svgs.txt # Saving file list into a file
      - name: Access cloned repository content
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add svgs.txt     
          git commit -am '[Auto] Refresh list of SVGs'
          git push https://${{secrets.METRO_GITHUB_TOKEN}}@github.com/lacmta/metro-iconography.git
